apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: minishop
spec:
  selector:
    app: order-service
  ports:
    - port: 3000          # Port dans le cluster
      targetPort: 3000    # Port dans le container
